DataFrame

In [1]:
D1 = {'name': ['nishant','mohit','divya','komal'],
      'age' : [25,20,30,26],
      'gender': ['M','M','F','F']
     }

In [2]:
import pandas as pd

In [3]:
pd.DataFrame(D1)

      name  age gender
0  nishant   25      M
1    mohit   20      M
2    divya   30      F
3    komal   26      F

In [4]:
i = ['a','b','c','d']
df = pd.DataFrame(D1,index=i)
df

      name  age gender
a  nishant   25      M
b    mohit   20      M
c    divya   30      F
d    komal   26      F

In [5]:
df.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [6]:
df['age']

a    25
b    20
c    30
d    26
Name: age, dtype: int64

In [7]:
df['name']

a    nishant
b      mohit
c      divya
d      komal
Name: name, dtype: object

In [8]:
df[['name','age']]

      name  age
a  nishant   25
b    mohit   20
c    divya   30
d    komal   26

In [9]:
type(df['name'])

pandas.core.series.Series

In [9]:
df[['name']]

      name
a  nishant
b    mohit
c    divya
d    komal

In [10]:
type(df[['name']])

pandas.core.frame.DataFrame

In [11]:
df.name.str.upper()

a    NISHANT
b      MOHIT
c      DIVYA
d      KOMAL
Name: name, dtype: object

In [14]:
df[['age']]

   age
a   25
b   20
c   30
d   26

In [77]:
df.name.get('b')

'mohit'

In [15]:
df.gender.get('d')

'F'

In [16]:
df.age.sum()

np.int64(101)

In [17]:
df.age.min()

20

In [18]:
df.age.max()

30

In [19]:
df.age.mean()

np.float64(25.25)

In [20]:
df['name'] == 'mohit'

a    False
b     True
c    False
d    False
Name: name, dtype: bool

In [21]:
df[df['name'] == 'mohit']

    name  age gender
b  mohit   20      M

In [22]:
df[df['age'] == 25]

      name  age gender
a  nishant   25      M

In [23]:
df[df['gender'] == 'M']

      name  age gender
a  nishant   25      M
b    mohit   20      M

In [24]:
df[df['age'] < 25]

    name  age gender
b  mohit   20      M

In [10]:
#Add New Column
#Address
address = ['Delhi','Noida','Sonipath','Delhi']
df['address'] = address
df

      name  age gender   address
a  nishant   25      M     Delhi
b    mohit   20      M     Noida
c    divya   30      F  Sonipath
d    komal   26      F     Delhi

In [26]:
#Indexing and Slicing
df[1:3]

    name  age gender   address
b  mohit   20      M     Noida
c  divya   30      F  Sonipath

In [27]:
df[0:4:2]

      name  age gender   address
a  nishant   25      M     Delhi
c    divya   30      F  Sonipath

In [28]:
#Importing DataSet Titanic_Dataset
data = pd.read_csv("Titanic-Dataset.csv")
s = data
s

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8f in position 22: invalid start byte

In [92]:
s.index

RangeIndex(start=0, stop=891, step=1)

In [93]:
s.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [94]:
s.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [95]:
s.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [96]:
s.sample(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
491,492,0,3,"Windelov, Mr. Einar",male,21.0,0,0,SOTON/OQ 3101317,7.2500,NaN,S
572,573,1,1,"Flynn, Mr. John Irwin (""Irving"")",male,36.0,0,0,PC 17474,26.3875,E25,S
156,157,1,3,"Gilnagh, Miss. Katherine ""Katie""",female,16.0,0,0,35851,7.7333,NaN,Q
358,359,1,3,"McGovern, Miss. Mary",female,NaN,0,0,330931,7.8792,NaN,Q
766,767,0,1,"Brewe, Dr. Arthur Jackson",male,NaN,0,0,112379,39.6000,NaN,C
432,433,1,2,"Louch, Mrs. Charles Alexander (Alice Adelaide ...",female,42.0,1,0,SC/AH 3085,26.0000,NaN,S
702,703,0,3,"Barbara, Miss. Saiide",female,18.0,0,1,2691,14.4542,NaN,C
214,215,0,3,"Kiernan, Mr. Philip",male,NaN,1,0,367229,7.7500,NaN,Q
591,592,1,1,"Stephenson, Mrs. Walter Bertram (Martha Eustis)",female,52.0,1,0,36947,78.2667,D20,C
276,277,0,3,"Lindblom, Miss. Augusta Charlotta",female,45.0,0,0,347073,7.7500,NaN,S

In [97]:
s.shape

(891, 12)

In [98]:
s.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [99]:
s.isna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [100]:
s.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [101]:
s.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [102]:
s.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Length: 891, dtype: bool

In [103]:
s.drop('PassengerId',axis=1)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [104]:
s.drop(columns=['Survived','Name','Sex'])

,PassengerId,Pclass,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,3,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,38.0,1,0,PC 17599,71.2833,C85,C
2,3,3,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,35.0,1,0,113803,53.1000,C123,S
4,5,3,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...
886,887,2,27.0,0,0,211536,13.0000,NaN,S
887,888,1,19.0,0,0,112053,30.0000,B42,S
888,889,3,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,26.0,0,0,111369,30.0000,C148,C
890,891,3,32.0,0,0,370376,7.7500,NaN,Q

In [105]:
s.drop(columns=['PassengerId','Name'],axis=1,inplace=True)

In [106]:
s

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,female,35.0,1,0,113803,53.1000,C123,S
4,0,3,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,211536,13.0000,NaN,S
887,1,1,female,19.0,0,0,112053,30.0000,B42,S
888,0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,1,1,male,26.0,0,0,111369,30.0000,C148,C
890,0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [108]:
s.drop(1,axis=0)

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,female,35.0,1,0,113803,53.1000,C123,S
4,0,3,male,35.0,0,0,373450,8.0500,NaN,S
5,0,3,male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,211536,13.0000,NaN,S
887,1,1,female,19.0,0,0,112053,30.0000,B42,S
888,0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,1,1,male,26.0,0,0,111369,30.0000,C148,C
890,0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [110]:
s.drop(index=[1,4,5,7,88,889],axis=0,inplace=True)

In [111]:
s

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,female,35.0,1,0,113803,53.1000,C123,S
6,0,1,male,54.0,0,0,17463,51.8625,E46,S
8,1,3,female,27.0,0,2,347742,11.1333,NaN,S
...,...,...,...,...,...,...,...,...,...,...
885,0,3,female,39.0,0,5,382652,29.1250,NaN,Q
886,0,2,male,27.0,0,0,211536,13.0000,NaN,S
887,1,1,female,19.0,0,0,112053,30.0000,B42,S
888,0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [112]:
s.info()

<class 'pandas.core.frame.DataFrame'>
Index: 885 entries, 0 to 890
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  885 non-null    int64
 1   Pclass    885 non-null    int64
 2   Sex       885 non-null    object
 3   Age       709 non-null    float64
 4   SibSp     885 non-null    int64
 5   Parch     885 non-null    int64
 6   Ticket    885 non-null    object
 7   Fare      885 non-null    float64
 8   Cabin     201 non-null    object
 9   Embarked  883 non-null    object
dtypes: float64(2), int64(4), object(4)
memory usage: 76.1+ KB

In [114]:
#Check Null Value
s.isna().sum()

Survived      0
Pclass        0
Sex           0
Age         176
SibSp         0
Parch         0
Ticket        0
Fare          0
Cabin       684
Embarked      2
dtype: int64

In [115]:
s.isna().mean()*100

Survived     0.000000
Pclass       0.000000
Sex          0.000000
Age         19.887006
SibSp        0.000000
Parch        0.000000
Ticket       0.000000
Fare         0.000000
Cabin       77.288136
Embarked     0.225989
dtype: float64

In [116]:
s.drop(columns=['Cabin'], axis=1,inplace=True)

In [117]:
s

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,0,3,male,22.0,1,0,A/5 21171,7.2500,S
2,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,1,1,female,35.0,1,0,113803,53.1000,S
6,0,1,male,54.0,0,0,17463,51.8625,S
8,1,3,female,27.0,0,2,347742,11.1333,S
...,...,...,...,...,...,...,...,...,...
885,0,3,female,39.0,0,5,382652,29.1250,Q
886,0,2,male,27.0,0,0,211536,13.0000,S
887,1,1,female,19.0,0,0,112053,30.0000,S
888,0,3,female,NaN,1,2,W./C. 6607,23.4500,S
890,0,3,male,32.0,0,0,370376,7.7500,Q

In [121]:
# s.dropna()

In [123]:
#Fill (mean,median,mode,random inputation, arbitry value,min,max...)

In [29]:
s['Age'].mean()
x = round(s['Age'].mean(),0)
x

NameError: name 's' is not defined

In [131]:
s['Age'] = s['Age'].fillna(x)

In [137]:
s.isna().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Ticket      0
Fare        0
Embarked    0
dtype: int64

In [136]:
s.dropna(inplace=True)

In [138]:
s.isna().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Ticket      0
Fare        0
Embarked    0
dtype: int64

#MAP

In [50]:
import pandas as pd
data = pd.read_csv("Titanic-Dataset.csv")
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [51]:
gender = {"male" : "M", "female":"F"}
data['Sex']=data['Sex'].map(gender,)

In [52]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",M,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",F,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",F,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",F,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",M,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",M,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",F,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",F,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",M,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",M,32.0,0,0,370376,7.7500,NaN,Q

In [53]:
embark = {"C":"Cherbourg", "Q":"Queenstown","S":"Southampton"}
data["Embarked"]=data["Embarked"].map(embark,)

In [54]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",M,22.0,1,0,A/5 21171,7.2500,NaN,Southampton
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",F,38.0,1,0,PC 17599,71.2833,C85,Cherbourg
2,3,1,3,"Heikkinen, Miss. Laina",F,26.0,0,0,STON/O2. 3101282,7.9250,NaN,Southampton
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",F,35.0,1,0,113803,53.1000,C123,Southampton
4,5,0,3,"Allen, Mr. William Henry",M,35.0,0,0,373450,8.0500,NaN,Southampton
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",M,27.0,0,0,211536,13.0000,NaN,Southampton
887,888,1,1,"Graham, Miss. Margaret Edith",F,19.0,0,0,112053,30.0000,B42,Southampton
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",F,NaN,1,2,W./C. 6607,23.4500,NaN,Southampton
889,890,1,1,"Behr, Mr. Karl Howell",M,26.0,0,0,111369,30.0000,C148,Cherbourg
890,891,0,3,"Dooley, Mr. Patrick",M,32.0,0,0,370376,7.7500,NaN,Queenstown

In [55]:
#Apply Function => apply()

In [56]:
data["Age"].isna().sum()

np.int64(177)

In [69]:
data["Age"].fillna(round(data["Age"].mean(),0),inplace=True)
data

/var/folders/5c/f9r2b96551jf7w4q0h_1xvj80000gn/T/ipykernel_1432/4230518741.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Age"].fillna(round(data["Age"].mean(),0),inplace=True)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",M,22,1,0,A/5 21171,7.2500,NaN,Southampton
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",F,38,1,0,PC 17599,71.2833,C85,Cherbourg
2,3,1,3,"Heikkinen, Miss. Laina",F,26,0,0,STON/O2. 3101282,7.9250,NaN,Southampton
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",F,35,1,0,113803,53.1000,C123,Southampton
4,5,0,3,"Allen, Mr. William Henry",M,35,0,0,373450,8.0500,NaN,Southampton
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",M,27,0,0,211536,13.0000,NaN,Southampton
887,888,1,1,"Graham, Miss. Margaret Edith",F,19,0,0,112053,30.0000,B42,Southampton
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",F,30,1,2,W./C. 6607,23.4500,NaN,Southampton
889,890,1,1,"Behr, Mr. Karl Howell",M,26,0,0,111369,30.0000,C148,Cherbourg
890,891,0,3,"Dooley, Mr. Patrick",M,32,0,0,370376,7.7500,NaN,Queenstown

In [63]:
data["Age"] = data["Age"].apply(lambda x:1 if x<1  else round(x,0))

In [64]:
data["Age"].iloc[305]

np.int64(1)

In [65]:

data["Age"] = data["Age"].astype("int")

In [66]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",M,22,1,0,A/5 21171,7.2500,NaN,Southampton
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",F,38,1,0,PC 17599,71.2833,C85,Cherbourg
2,3,1,3,"Heikkinen, Miss. Laina",F,26,0,0,STON/O2. 3101282,7.9250,NaN,Southampton
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",F,35,1,0,113803,53.1000,C123,Southampton
4,5,0,3,"Allen, Mr. William Henry",M,35,0,0,373450,8.0500,NaN,Southampton
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",M,27,0,0,211536,13.0000,NaN,Southampton
887,888,1,1,"Graham, Miss. Margaret Edith",F,19,0,0,112053,30.0000,B42,Southampton
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",F,30,1,2,W./C. 6607,23.4500,NaN,Southampton
889,890,1,1,"Behr, Mr. Karl Howell",M,26,0,0,111369,30.0000,C148,Cherbourg
890,891,0,3,"Dooley, Mr. Patrick",M,32,0,0,370376,7.7500,NaN,Queenstown

In [67]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    int64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(1), int64(6), object(5)
memory usage: 83.7+ KB

transform()

In [70]:
data["Fare"].transform(lambda x:x*88.68)

0       642.930000
1      6321.403044
2       702.789000
3      4708.908000
4       713.874000
          ...
886    1152.840000
887    2660.400000
888    2079.546000
889    2660.400000
890     687.270000
Name: Fare, Length: 891, dtype: float64

In [73]:
data["Fare"]=data["Fare"].transform(lambda x:x*88.68)

In [78]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",M,22,1,0,A/5 21171,57015.032400,NaN,Southampton
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",F,38,1,0,PC 17599,560582.021942,C85,Cherbourg
2,3,1,3,"Heikkinen, Miss. Laina",F,26,0,0,STON/O2. 3101282,62323.328520,NaN,Southampton
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",F,35,1,0,113803,417585.961440,C123,Southampton
4,5,0,3,"Allen, Mr. William Henry",M,35,0,0,373450,63306.346320,NaN,Southampton
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",M,27,0,0,211536,102233.851200,NaN,Southampton
887,888,1,1,"Graham, Miss. Margaret Edith",F,19,0,0,112053,235924.272000,B42,Southampton
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",F,30,1,2,W./C. 6607,184414.139280,NaN,Southampton
889,890,1,1,"Behr, Mr. Karl Howell",M,26,0,0,111369,235924.272000,C148,Cherbourg
890,891,0,3,"Dooley, Mr. Patrick",M,32,0,0,370376,60947.103600,NaN,Queenstown

In [79]:
#Sort_Values()
data["Fare"]=data["Fare"].sort_values(ascending=False)

In [80]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",M,22,1,0,A/5 21171,57015.032400,NaN,Southampton
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",F,38,1,0,PC 17599,560582.021942,C85,Cherbourg
2,3,1,3,"Heikkinen, Miss. Laina",F,26,0,0,STON/O2. 3101282,62323.328520,NaN,Southampton
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",F,35,1,0,113803,417585.961440,C123,Southampton
4,5,0,3,"Allen, Mr. William Henry",M,35,0,0,373450,63306.346320,NaN,Southampton
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",M,27,0,0,211536,102233.851200,NaN,Southampton
887,888,1,1,"Graham, Miss. Margaret Edith",F,19,0,0,112053,235924.272000,B42,Southampton
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",F,30,1,2,W./C. 6607,184414.139280,NaN,Southampton
889,890,1,1,"Behr, Mr. Karl Howell",M,26,0,0,111369,235924.272000,C148,Cherbourg
890,891,0,3,"Dooley, Mr. Patrick",M,32,0,0,370376,60947.103600,NaN,Queenstown

In [81]:
data.sort_values(by="Age" , ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",M,80,0,0,27042,235924.272000,A23,Southampton
851,852,0,3,"Svensson, Mr. Johan",M,74,0,0,347060,61143.707160,NaN,Southampton
493,494,0,1,"Artagaveytia, Mr. Ramon",M,71,0,0,PC 17609,389308.078198,NaN,Cherbourg
96,97,0,1,"Goldschmidt, Mr. George B",M,71,0,0,PC 17754,272525.563558,A5,Cherbourg
745,746,0,1,"Crosby, Capt. Edward Gifford",M,70,1,1,WE/P 5735,558354.110400,B22,Southampton
...,...,...,...,...,...,...,...,...,...,...,...,...
469,470,1,3,"Baclini, Miss. Helene Barbara",F,1,2,1,2666,151450.013582,NaN,Cherbourg
788,789,1,3,"Dean, Master. Bertram Vere",M,1,1,2,C.A. 2315,161804.729880,NaN,Southampton
386,387,0,3,"Goodwin, Master. Sidney Leonard",M,1,5,2,CA 2144,368828.278560,NaN,Southampton
381,382,1,3,"Nakid, Miss. Maria (""Mary"")",F,1,0,2,2653,123794.970418,NaN,Cherbourg
183,184,1,2,"Becker, Master. Richard F",M,1,2,1,230136,306701.553600,F4,Southampton