In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./employee_productivity.csv')
df

    Emp_ID       Dept  Hours_Worked  Tasks_Completed  Satisfaction_Rating
0     E001      Sales           7.5               12                    8
1     E002         HR           6.0                8                    7
2     E003         IT           8.5               15                    9
3     E004    Finance           7.0               10                    6
4     E005      Sales           9.0               18                    9
..     ...        ...           ...              ...                  ...
115   E116    Finance           7.1                9                    7
116   E117         HR           5.9                6                    5
117   E118  Marketing           8.0               14                    8
118   E119      Sales           8.6               15                    8
119   E120         IT           8.8               17                    9

[120 rows x 5 columns]

In [3]:
# 1. The HR manager wants to know which department has the highest average working hours. Use groupby to
# calculate the average Hours_Worked for each department.
df.groupby("Dept")["Hours_Worked"].mean()

Dept
Finance      7.254167
HR           6.047826
IT           8.632000
Marketing    8.039130
Sales        8.348000
Name: Hours_Worked, dtype: float64

In [4]:
#2 The CEO wants a department-wise breakdown of total productivity. Calculate the total Tasks_Completed for
#. each department.

total_productivity= df.groupby("Dept")["Tasks_Completed"].sum().sort_values(ascending=False)
pd.DataFrame(total_productivity)

           Tasks_Completed
Dept
IT                     405
Sales                  375
Marketing              316
Finance                224
HR                     141

In [5]:
# 3. The employee engagement team wants to identify the happiest department. Find the maximum
# Satisfaction_Rating per department.
df.groupby("Dept")["Satisfaction_Rating"].max()

Dept
Finance       8
HR            7
IT           10
Marketing     9
Sales         9
Name: Satisfaction_Rating, dtype: int64

In [6]:
# 4. HR wants to know how many employees work in each department for manpower planning. Count employees
# per department.
df.groupby("Dept")["Emp_ID"].count()

Dept
Finance      24
HR           23
IT           25
Marketing    23
Sales        25
Name: Emp_ID, dtype: int64

In [7]:
# 5. The operations head wants to review overall task distribution. Find the mean and sum of Tasks_Completed per
# department.
df.groupby("Dept")["Tasks_Completed"].agg(["mean","sum"])

                mean  sum
Dept
Finance     9.333333  224
HR          6.130435  141
IT         16.200000  405
Marketing  13.739130  316
Sales      15.000000  375

In [8]:
# 6. Management wants to evaluate which department is balanced in both efficiency and happiness. Compute
# average Hours_Worked and average Satisfaction_Rating per department.
df.groupby("Dept")[["Hours_Worked","Satisfaction_Rating"]].mean()

           Hours_Worked  Satisfaction_Rating
Dept
Finance        7.254167             6.750000
HR             6.047826             5.304348
IT             8.632000             8.880000
Marketing      8.039130             8.130435
Sales          8.348000             8.120000

In [9]:
# 7. HR wants to find underperforming units. Identify the minimum Hours_Worked in each department.
df.groupby("Dept")["Hours_Worked"].min()

Dept
Finance      6.8
HR           5.5
IT           7.7
Marketing    6.5
Sales        7.0
Name: Hours_Worked, dtype: float64

In [10]:
# 8. The finance team wants to understand work variability. Calculate the standard deviation of Hours_Worked for
# each department.
df.groupby("Dept")["Hours_Worked"].std()

Dept
Finance      0.232153
HR           0.292123
IT           0.392343
Marketing    0.432476
Sales        0.640391
Name: Hours_Worked, dtype: float64

In [11]:
# 9. For award distribution, get the first employee (by order in dataset) from each department.
df.groupby("Dept").first()

          Emp_ID  Hours_Worked  Tasks_Completed  Satisfaction_Rating
Dept
Finance     E004           7.0               10                    6
HR          E002           6.0                8                    7
IT          E003           8.5               15                    9
Marketing   E006           6.5                9                    7
Sales       E001           7.5               12                    8

In [12]:
# 10. The productivity analyst wants the median number of tasks completed in each department.
df.groupby("Dept")["Tasks_Completed"].median()

Dept
Finance       9.0
HR            6.0
IT           16.0
Marketing    14.0
Sales        15.0
Name: Tasks_Completed, dtype: float64

In [13]:
# 11. HR wants to know how many highly satisfied employees (Satisfaction_Rating ≥ 8) exist in each department.
df[df["Satisfaction_Rating"] >= 8].groupby("Dept").size()

Dept
Finance       3
IT           24
Marketing    20
Sales        18
dtype: int64

In [14]:
# 12. The performance manager wants to know how many employees in each department worked more than 8 hours.
df[df["Hours_Worked"] >= 8].groupby("Dept").size()

Dept
IT           23
Marketing    16
Sales        18
dtype: int64

In [15]:
# 13. The culture team wants to understand how satisfaction accumulates by department. Calculate total
# Satisfaction_Rating for each department.
df.groupby("Dept")["Satisfaction_Rating"].sum()

Dept
Finance      162
HR           122
IT           222
Marketing    187
Sales        203
Name: Satisfaction_Rating, dtype: int64

In [16]:
# 14. HR wants to analyze satisfaction levels in detail. For each department, get the frequency of each
# Satisfaction_Rating.
df.groupby("Dept")["Satisfaction_Rating"].value_counts().unstack(fill_value=0)

Satisfaction_Rating  4   5   6   7   8   9   10
Dept
Finance               0   0   9  12   3   0   0
HR                    4  10   7   2   0   0   0
IT                    0   0   1   0   7  10   7
Marketing             0   0   0   3  14   6   0
Sales                 0   0   1   6   7  11   0

In [33]:
# 15. The CEO wants to meet the top performer in each department. Identify the employee with maximum
# Tasks_Completed per department using idxmax().
df.groupby("Dept")["Tasks_Completed"].max()

Dept
Finance      11
HR            8
IT           21
Marketing    15
Sales        19
Name: Tasks_Completed, dtype: int64

In [18]:
# 16. Managers want to evaluate top contributors. List the top 3 employees with highest Hours_Worked per
# department.
df.sort_values("Hours_Worked", ascending=False).groupby("Dept").head(3)

    Emp_ID       Dept  Hours_Worked  Tasks_Completed  Satisfaction_Rating
84    E085         IT           9.2               21                   10
33    E034      Sales           9.2               19                    9
24    E025         IT           9.1               18                   10
104   E105         IT           9.1               20                   10
68    E069      Sales           9.1               19                    9
4     E005      Sales           9.0               18                    9
112   E113  Marketing           8.5               15                    9
37    E038  Marketing           8.5               14                    8
17    E018  Marketing           8.4               14                    8
45    E046    Finance           7.7               11                    8
85    E086    Finance           7.6               10                    7
20    E021    Finance           7.6               10                    8
96    E097         HR           6.5                7                    6
56    E057         HR           6.5                6                    6
71    E072         HR           6.4                7                    6

In [19]:
# 17. The analytics team wants to check if longer working hours actually increase productivity. Calculate correlation
# between Hours_Worked and Tasks_Completed within each department.
df.groupby("Dept").apply(lambda x:x["Hours_Worked"].corr(x["Tasks_Completed"]))

/var/folders/5c/f9r2b96551jf7w4q0h_1xvj80000gn/T/ipykernel_1179/3839059305.py:3: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby("Dept").apply(lambda x:x["Hours_Worked"].corr(x["Tasks_Completed"]))

Dept
Finance      0.618626
HR           0.583639
IT           0.902099
Marketing    0.872921
Sales        0.952703
dtype: float64

In [20]:
# 18. HR wants the most recently added employee from each department. Retrieve the last record per department.

In [21]:
# 19. Team leaders want to see how workload accumulates over time. Calculate cumulative sum of Tasks_Completed
# within each department.

In [22]:
# 20. Management wants to study how average working hours evolve. Calculate cumulative mean of Hours_Worked
# per department.

In [23]:
# 21. HR wants to compare employees relative to their department peers. Transform Hours_Worked into z-scores
# within each department.

In [24]:
# 22. The operations team wants to see each employee’s contribution to department productivity. Convert
# Tasks_Completed into percent contribution using groupby transform.

In [25]:
# 23. Management wants to appreciate high-morale teams. Filter and display departments where average
# Satisfaction_Rating is above 8.

In [32]:
# 24. The CEO wants to reward the most hardworking department. Identify departments where total
# Tasks_Completed is greater than 200.
df[df["Tasks_Completed"] >= 200].groupby("Dept")["Tasks_Completed"].sum()

Series([], Name: Tasks_Completed, dtype: int64)

In [27]:
# 25. HR wants to check department size distribution. Use groupby to return the size of each department.
df.groupby("Dept").size()

Dept
Finance      24
HR           23
IT           25
Marketing    23
Sales        25
dtype: int64